
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: oadp-operator
  namespace: openshift-adp
spec:
  channel: stable
  name: oadp-operator
  source: redhat-operators-mirror
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

